### ISSUE TITLE
Auto-discovery of devices

### ISSUE THREAD

**Issue by marvinroger** [marvinroger/homie-server#3]
Going forward, devices will be recognized automatically using mDNS. People would then access a page on the dashboard to accept or refuse devices.

**Comment by marvinroger** [comment]
Why did I talked about mDNS? No need to, as the devices are configured to reach the MQTT broker.

**Comment by oguime** [comment]
Hi Marvin,
Can the Homie convention and Homie-Server be used with devices other than the ESP8266? Would they work with Hue lights or ZWave devices?

**Comment by marvinroger** [comment]
Simply put, you would have to create a "bridge" between your devices and the convention. Node-RED might help, with https://github.com/marvinroger/node-red-contrib-homie, but this is not documented for now.

**Comment by oguime** [comment]
![homie](https://cloud.githubusercontent.com/assets/5217023/15265068/88be3d78-1952-11e6-8188-550e8e2f94b4.png)

Hi Marvin, I do use Node-RED and even played a little with it, but could not do much...

Would it enable controlling other devices with homie-server?

**Comment by marvinroger** [comment]
If you intend to use `homie-server`, the only things it supports for light is on or off, there is no support for colors right now. And I am afraid I won't work on this project before a while.

**Comment by oguime** [comment]
Color support is not important right now, I'll give it a try...

I got a error on Homie-server start:

2016-05-14T14:35:16.472Z fatal: GUI server cannot listen

**Comment by marvinroger** [comment]
You probably have something already listening on port 80, try another port.

**Comment by marvinroger** [comment]
Hi! I'm going to archive this project, as I'm not maintaining it anymore.
Looking forward to Matter!
