### ISSUE TITLE
Syntax of infrastructure.yml file for v0.4.9

### ISSUE THREAD

**Issue by NigelTwo** [marvinroger/homie-server#6]
The default infrastructure.yml file for v0.4.9 has square brackets in it:
devices: []
groups: []
Has this changed?, because the example given in the homie-server notes gives an error.
Thank you for this project.

**Comment by marvinroger** [comment]
No it has not changed, I just forgot a `-` in the README. I corrected the typo, thanks!

**Comment by NigelTwo** [comment]
Yes, that has fixed it ;-)
