### ISSUE TITLE
Add support for dimmable, rgb lights

### ISSUE THREAD

**Issue by unaiur** [marvinroger/homie-server#8]
I would like to add "traits" to HomieNode.

For example, in case of a light, if it has no traits property, only "on" property is mandatory. But if I add a trait property with the value "dimmable,rgb" it will also expose the properties "brightness" and "color".

This read-only property may be added to any node type to extend its semantic.

**Comment by marvinroger** [comment]
Well, this project is still in a very early state, but you're right, this UI is currently not configurable at all. We'll have to change that! Unfortunately I have no time to work on this for the moment, but I'll work on it again, when I have more time.

**Comment by marvinroger** [comment]
Hi! I'm going to archive this project, as I'm not maintaining it anymore.
Looking forward to Matter!
