### ISSUE TITLE
Make it as a npm module for import into app

### ISSUE THREAD

**Issue by mishoboss** [marvinroger/homie-server#9]
As I see, currently the server can be run only as cli and read the config from <homeDir>/.homie. I would love to be able to import it into my app and provide config as object. Is there a chance for that?

**Comment by marvinroger** [comment]
There is definitely a chance for that! I have little time right now, so I prefer to work on homie-esp8266. When I'll be a little bit more free, I will work on this projet again. :)

**Comment by marvinroger** [comment]
Hi! I'm going to archive this project, as I'm not maintaining it anymore.
Looking forward to Matter!
